name: Generate Snake Grid

on:
  push:
    branches:
      - main # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: webdevaminul
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload snake grid
        uses: actions/upload-artifact@v2
        with:
          name: snake-grid
          path: dist/github-contribution-grid-snake.svg
